### ISSUE TITLE
Need some help for generating rrd.

### ISSUE THREAD

**Issue by RAMMVIER** [bkiers/rrd-antlr4#12]
@bkiers 

I was trying to use this project to generate a rrd of json with the commands provided in README.md. 
But I encountered:

```
parsing: JSON.g4 ...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at nl.bigo.rrdantlr4.Main.main(Main.java:46)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "nl.bigo.rrdantlr4.DiagramGenerator.ENGINE" is null
	at nl.bigo.rrdantlr4.DiagramGenerator.<clinit>(DiagramGenerator.java:55)
	... 1 more
```

Any suggestions of how I could get around this would be appreciated. Thank you!

**Comment by danspeck** [comment]
I just followed the instructions in the README.md and it worked fine on my
Mac. Could you post more information about your environment and the command
line you used?

-dan

**Comment by bkiers** [comment]
It appears that since Java 11, the Rhino engine is no longer shipped in the JDK/JRE, and therefor `MANAGER.getEngineByName("JavaScript")` returns `null`. See: http://openjdk.java.net/jeps/335

I'll have a look at this.
